use_default_settings: true

general:
  instance_name: "Regex Discord Search"
  enable_metrics: false

search:
  safe_search: 0
  default_lang: "vi-VN"
  formats:
    - html
    - json

server:
  secret_key: __SEARXNG_SECRET_JSON__
__SEARXNG_BASE_URL_LINE__
  bind_address: "0.0.0.0"
  limiter: false
  public_instance: false
  image_proxy: true
  method: "GET"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

ui:
  default_locale: "vi"
  default_theme: simple
  theme_args:
    simple_style: auto
  results_on_new_tab: true
  search_on_category_select: true

outgoing:
  request_timeout: 3.0
  max_request_timeout: 8.0
  enable_http2: true

engines:
  - name: google images
    disabled: false
    language: vi-VN
    timeout: 4.0
    weight: 3.0

  - name: bing images
    disabled: false
    language: vi-VN
    timeout: 3.0
    weight: 0.8

  - name: duckduckgo images
    disabled: false
    language: vi-VN
    timeout: 3.0
    weight: 0.8

  - name: qwant images
    disabled: true

  - name: brave.images
    disabled: true

  - name: yandex images
    disabled: true
